#!/usr/bin/env npx tsx
/**
 * User Guide Index Generator
 *
 * Parses docs/ai/test-cases/input/user-guide.md and produces a TOC with
 * anchors + line ranges into docs/ai/knowledge-base/corpus/user-guide-index.md.
 *
 * The agent reads ranges with `read_file(startLine, endLine)` — never the whole UG.
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const ROOT = path.resolve(__dirname, '..');
const SOURCE = path.join(ROOT, 'docs', 'ai', 'test-cases', 'input', 'user-guide.md');
const OUTPUT = path.join(
  ROOT,
  'docs',
  'ai',
  'knowledge-base',
  'corpus',
  'user-guide-index.md',
);
const SYNC_STATE = path.join(ROOT, 'docs', 'ai', 'knowledge-base', '.sync-state.json');

interface Heading {
  level: number;
  text: string;
  anchor: string;
  startLine: number;
  endLine: number;
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

function main(): void {
  if (!fs.existsSync(SOURCE)) {
    console.warn(
      `User Guide not found at ${SOURCE} — skipping index. Convert the User Guide to markdown and re-run.`,
    );
    return;
  }
  const raw = fs.readFileSync(SOURCE, 'utf8');
  const lines = raw.split('\n');
  const headings: Heading[] = [];

  for (let i = 0; i < lines.length; i++) {
    const m = /^(#{1,3})\s+(.+?)\s*$/.exec(lines[i]);
    if (!m) continue;
    headings.push({
      level: m[1].length,
      text: m[2].trim(),
      anchor: slugify(m[2]),
      startLine: i + 1,
      endLine: lines.length,
    });
  }

  for (let i = 0; i < headings.length - 1; i++) {
    headings[i].endLine = headings[i + 1].startLine - 1;
  }

  const out: string[] = [];
  out.push('# User Guide Index');
  out.push('');
  out.push('> Generated by `scripts/index-user-guide.ts`. Do not edit by hand.');
  out.push(
    '> Source: `docs/ai/test-cases/input/user-guide.md`. Read sections via `read_file` with the listed line range.',
  );
  out.push('');
  out.push('| Anchor | Heading | Level | Lines |');
  out.push('|---|---|---|---|');
  for (const h of headings) {
    const indent = '  '.repeat(h.level - 1);
    out.push(
      `| \`${h.anchor}\` | ${indent}${escapePipes(h.text)} | H${h.level} | ${h.startLine}–${h.endLine} |`,
    );
  }
  out.push('');

  fs.writeFileSync(OUTPUT, out.join('\n'), 'utf8');
  updateSyncState(raw);

  console.log(`Wrote ${OUTPUT} — ${headings.length} headings.`);
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function updateSyncState(raw: string): void {
  if (!fs.existsSync(SYNC_STATE)) return;
  const state = JSON.parse(fs.readFileSync(SYNC_STATE, 'utf8'));
  state.userGuide ??= {};
  state.userGuide.source = 'docs/ai/test-cases/input/user-guide.md';
  state.userGuide.lastIndexed = new Date().toISOString();
  state.userGuide.sha256 = crypto.createHash('sha256').update(raw).digest('hex');
  fs.writeFileSync(SYNC_STATE, JSON.stringify(state, null, 2) + '\n', 'utf8');
}

main();
