#!/usr/bin/env npx tsx
/**
 * User Guides Index Generator
 *
 * Walks docs/ai/knowledge-base/user-guides/*.md and writes a per-file TOC
 * with anchors + line ranges into
 * docs/ai/knowledge-base/corpus/user-guide-index.md.
 *
 * Agent reads sections via `read_file(startLine, endLine)` — never the whole
 * guide. Convert any .docx siblings with pandoc first.
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const ROOT = path.resolve(__dirname, '..');
const SOURCE_DIR = path.join(ROOT, 'docs', 'ai', 'knowledge-base', 'user-guides');
const OUTPUT = path.join(
  ROOT,
  'docs',
  'ai',
  'knowledge-base',
  'corpus',
  'user-guide-index.md',
);
const SYNC_STATE = path.join(ROOT, 'docs', 'ai', 'knowledge-base', '.sync-state.json');

interface Heading {
  level: number;
  text: string;
  anchor: string;
  startLine: number;
  endLine: number;
}

interface Entry {
  file: string;
  abs: string;
  lineCount: number;
  headings: Heading[];
  sha256: string;
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

function parseHeadings(raw: string): Heading[] {
  const lines = raw.split('\n');
  const out: Heading[] = [];
  for (let i = 0; i < lines.length; i++) {
    const m = /^(#{1,4})\s+(.+?)\s*$/.exec(lines[i]);
    if (!m) continue;
    out.push({
      level: m[1].length,
      text: m[2].trim(),
      anchor: slugify(m[2]),
      startLine: i + 1,
      endLine: lines.length,
    });
  }
  for (let i = 0; i < out.length - 1; i++) {
    out[i].endLine = out[i + 1].startLine - 1;
  }
  return out;
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, '\\|');
}

function relPath(abs: string): string {
  return path.relative(ROOT, abs).split(path.sep).join('/');
}

function main(): void {
  if (!fs.existsSync(SOURCE_DIR)) {
    console.warn(`User-guides directory not found at ${SOURCE_DIR} — skipping.`);
    return;
  }
  const files = fs
    .readdirSync(SOURCE_DIR)
    .filter((n) => n.toLowerCase().endsWith('.md'))
    .sort();

  if (files.length === 0) {
    console.warn(`No .md files in ${SOURCE_DIR}. Convert .docx via pandoc first.`);
    return;
  }

  const entries: Entry[] = files.map((name) => {
    const abs = path.join(SOURCE_DIR, name);
    const raw = fs.readFileSync(abs, 'utf8');
    return {
      file: name,
      abs,
      lineCount: raw.split('\n').length,
      headings: parseHeadings(raw),
      sha256: crypto.createHash('sha256').update(raw).digest('hex'),
    };
  });

  const out: string[] = [];
  out.push('# User Guides Index');
  out.push('');
  out.push('> Generated by `scripts/index-user-guide.ts`. Do not edit by hand.');
  out.push(
    '> Sources: `docs/ai/knowledge-base/user-guides/*.md`. Read sections via `read_file` with the listed line range.',
  );
  out.push('');
  out.push('## Files');
  out.push('');
  out.push('| # | File | Lines | Headings |');
  out.push('|---|---|---|---|');
  entries.forEach((e, i) => {
    out.push(`| ${i + 1} | \`${e.file}\` | ${e.lineCount} | ${e.headings.length} |`);
  });
  out.push('');

  for (const e of entries) {
    out.push(`## \`${e.file}\``);
    out.push('');
    out.push(`Path: \`${relPath(e.abs)}\``);
    out.push('');
    out.push('| Anchor | Heading | Level | Lines |');
    out.push('|---|---|---|---|');
    for (const h of e.headings) {
      const indent = '  '.repeat(h.level - 1);
      out.push(
        `| \`${h.anchor}\` | ${indent}${escapePipes(h.text)} | H${h.level} | ${h.startLine}–${h.endLine} |`,
      );
    }
    out.push('');
  }

  fs.writeFileSync(OUTPUT, out.join('\n'), 'utf8');
  updateSyncState(entries);
  const total = entries.reduce((s, e) => s + e.headings.length, 0);
  console.log(`Wrote ${OUTPUT} — ${entries.length} files, ${total} headings.`);
}

function updateSyncState(entries: Entry[]): void {
  if (!fs.existsSync(SYNC_STATE)) return;
  const state = JSON.parse(fs.readFileSync(SYNC_STATE, 'utf8'));
  state.userGuides = {
    sourceDir: 'docs/ai/knowledge-base/user-guides',
    lastIndexed: new Date().toISOString(),
    files: entries.map((e) => ({ file: e.file, lines: e.lineCount, sha256: e.sha256 })),
  };
  delete state.userGuide;
  fs.writeFileSync(SYNC_STATE, JSON.stringify(state, null, 2) + '\n', 'utf8');
}

main();
