#!/usr/bin/env npx tsx
/**
 * Jira Stories Index Generator
 *
 * Fetches user-story metadata for project PIC, excluding `On-hold` and `Rejected`
 * statuses, and writes docs/ai/knowledge-base/corpus/jira-stories-index.md.
 *
 * Metadata only: key, summary, status, priority, fixVersions, labels, assignee,
 * updated. Bodies/ACs are fetched on demand via jira_get_issue(key=…).
 *
 * Usage:
 *   npx tsx scripts/index-jira-stories.ts
 *   npx tsx scripts/index-jira-stories.ts --project PIC --limit 5000
 *   npx tsx scripts/index-jira-stories.ts --jql 'project=PIC AND type=Story'
 */

import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '..');
const OUTPUT = path.join(
  ROOT,
  'docs',
  'ai',
  'knowledge-base',
  'corpus',
  'jira-stories-index.md',
);
const SYNC_STATE = path.join(ROOT, 'docs', 'ai', 'knowledge-base', '.sync-state.json');

interface Args {
  project: string;
  jql: string | null;
  limit: number;
  dryRun: boolean;
}

interface StoryMeta {
  key: string;
  summary: string;
  status: string;
  priority: string;
  fixVersions: string[];
  labels: string[];
  assignee: string;
  updated: string;
}

function parseArgs(argv: string[]): Args {
  const args: Args = { project: 'PIC', jql: null, limit: 10000, dryRun: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--project') args.project = argv[++i];
    else if (a === '--jql') args.jql = argv[++i];
    else if (a === '--limit') args.limit = Number(argv[++i]);
    else if (a === '--dry-run') args.dryRun = true;
  }
  return args;
}

async function searchJql(
  base: string,
  auth: string,
  jql: string,
  limit: number,
): Promise<StoryMeta[]> {
  const out: StoryMeta[] = [];
  const pageSize = 100;
  let start = 0;
  while (out.length < limit) {
    const url = `${base}/rest/api/2/search?jql=${encodeURIComponent(jql)}&startAt=${start}&maxResults=${pageSize}&fields=summary,status,priority,fixVersions,labels,assignee,updated`;
    const res = await fetch(url, {
      headers: { Authorization: auth, Accept: 'application/json' },
    });
    if (!res.ok) {
      throw new Error(`GET ${url} → ${res.status} ${res.statusText}`);
    }
    const body = (await res.json()) as any;
    const issues = Array.isArray(body?.issues) ? body.issues : [];
    if (issues.length === 0) break;
    for (const i of issues) {
      out.push({
        key: String(i.key),
        summary: String(i?.fields?.summary ?? ''),
        status: String(i?.fields?.status?.name ?? ''),
        priority: String(i?.fields?.priority?.name ?? ''),
        fixVersions: (i?.fields?.fixVersions ?? []).map((v: any) => String(v?.name ?? '')),
        labels: (i?.fields?.labels ?? []).map(String),
        assignee: String(i?.fields?.assignee?.displayName ?? ''),
        updated: String(i?.fields?.updated ?? ''),
      });
      if (out.length >= limit) break;
    }
    const total = Number(body?.total ?? 0);
    if (start + issues.length >= total) break;
    start += issues.length;
    if (out.length % 500 === 0) console.log(`  ...${out.length} issues fetched`);
  }
  return out;
}

function writeIndex(issues: StoryMeta[], jql: string): void {
  issues.sort((a, b) => a.key.localeCompare(b.key, undefined, { numeric: true }));
  const out: string[] = [];
  out.push('# Jira Stories Index');
  out.push('');
  out.push('> Generated by `scripts/index-jira-stories.ts`. Do not edit by hand.');
  out.push(
    '> Metadata only. Fetch body + ACs via `jira_get_issue(key=…)` through Atlassian MCP.',
  );
  out.push(`> JQL: \`${jql}\``);
  out.push('');
  out.push('| Key | Summary | Status | Priority | Fix Version(s) | Labels | Assignee | Updated |');
  out.push('|---|---|---|---|---|---|---|---|');
  for (const i of issues) {
    const summary = i.summary.replace(/\|/g, '\\|');
    const fixV = i.fixVersions.join('; ');
    const labels = i.labels.join(' ');
    out.push(
      `| ${i.key} | ${summary} | ${i.status} | ${i.priority} | ${fixV} | ${labels} | ${i.assignee} | ${i.updated} |`,
    );
  }
  out.push('');
  fs.writeFileSync(OUTPUT, out.join('\n'), 'utf8');
}

function updateSyncState(count: number, jql: string): void {
  if (!fs.existsSync(SYNC_STATE)) return;
  const state = JSON.parse(fs.readFileSync(SYNC_STATE, 'utf8'));
  state.jiraStories = {
    jql,
    count,
    lastIndexed: new Date().toISOString(),
  };
  fs.writeFileSync(SYNC_STATE, JSON.stringify(state, null, 2) + '\n', 'utf8');
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const base = process.env.JIRA_BASE_URL ?? process.env.JIRA_URL ?? '';
  const email = process.env.JIRA_EMAIL ?? process.env.JIRA_USERNAME ?? '';
  const token = process.env.JIRA_API_TOKEN ?? '';

  if (!base || !email || !token) {
    console.error(
      'Missing JIRA_BASE_URL / JIRA_EMAIL / JIRA_API_TOKEN. Source your .env first.',
    );
    process.exit(2);
  }
  const auth = 'Basic ' + Buffer.from(`${email}:${token}`).toString('base64');

  const jql =
    args.jql ??
    `project = ${args.project} AND issuetype = Story AND status NOT IN ("On-hold", "Rejected") ORDER BY updated DESC`;

  console.log(`Fetching stories via JQL (limit=${args.limit}):\n  ${jql}\n`);

  let issues: StoryMeta[];
  try {
    issues = await searchJql(base, auth, jql, args.limit);
  } catch (err) {
    console.error(`Jira fetch failed: ${(err as Error).message}`);
    process.exit(1);
  }

  if (args.dryRun) {
    console.log(`Would write ${issues.length} rows to ${OUTPUT}`);
    return;
  }

  writeIndex(issues, jql);
  updateSyncState(issues.length, jql);
  console.log(`Wrote ${OUTPUT} — ${issues.length} stories indexed.`);
}

main();
