#!/usr/bin/env npx tsx
/**
 * Jira Tests Index Generator
 *
 * Fetches Test-issue metadata for project PIC and writes
 * docs/ai/knowledge-base/corpus/jira-tests-index.md.
 *
 * Metadata only: key, summary, status, priority, labels, components, updated.
 * Full steps/definitions fetched on demand via jira_get_issue(key=…).
 *
 * Usage:
 *   npx tsx scripts/index-jira-tests.ts
 *   npx tsx scripts/index-jira-tests.ts --project PIC --limit 5000
 */

import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '..');
const OUTPUT = path.join(
  ROOT,
  'docs',
  'ai',
  'knowledge-base',
  'corpus',
  'jira-tests-index.md',
);
const SYNC_STATE = path.join(ROOT, 'docs', 'ai', 'knowledge-base', '.sync-state.json');

interface Args {
  project: string;
  jql: string | null;
  limit: number;
  dryRun: boolean;
}

interface TestMeta {
  key: string;
  summary: string;
  status: string;
  priority: string;
  labels: string[];
  components: string[];
  updated: string;
}

function parseArgs(argv: string[]): Args {
  const args: Args = { project: 'PIC', jql: null, limit: 10000, dryRun: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--project') args.project = argv[++i];
    else if (a === '--jql') args.jql = argv[++i];
    else if (a === '--limit') args.limit = Number(argv[++i]);
    else if (a === '--dry-run') args.dryRun = true;
  }
  return args;
}

async function searchJql(
  base: string,
  auth: string,
  jql: string,
  limit: number,
): Promise<TestMeta[]> {
  const out: TestMeta[] = [];
  const pageSize = 100;
  let start = 0;
  while (out.length < limit) {
    const url = `${base}/rest/api/2/search?jql=${encodeURIComponent(jql)}&startAt=${start}&maxResults=${pageSize}&fields=summary,status,priority,labels,components,updated`;
    const res = await fetch(url, {
      headers: { Authorization: auth, Accept: 'application/json' },
    });
    if (!res.ok) {
      throw new Error(`GET ${url} → ${res.status} ${res.statusText}`);
    }
    const body = (await res.json()) as any;
    const issues = Array.isArray(body?.issues) ? body.issues : [];
    if (issues.length === 0) break;
    for (const i of issues) {
      out.push({
        key: String(i.key),
        summary: String(i?.fields?.summary ?? ''),
        status: String(i?.fields?.status?.name ?? ''),
        priority: String(i?.fields?.priority?.name ?? ''),
        labels: (i?.fields?.labels ?? []).map(String),
        components: (i?.fields?.components ?? []).map((c: any) => String(c?.name ?? '')),
        updated: String(i?.fields?.updated ?? ''),
      });
      if (out.length >= limit) break;
    }
    const total = Number(body?.total ?? 0);
    if (start + issues.length >= total) break;
    start += issues.length;
    if (out.length % 1000 === 0) console.log(`  ...${out.length} tests fetched`);
  }
  return out;
}

function writeIndex(issues: TestMeta[], jql: string): void {
  issues.sort((a, b) => a.key.localeCompare(b.key, undefined, { numeric: true }));
  const out: string[] = [];
  out.push('# Jira Tests Index');
  out.push('');
  out.push('> Generated by `scripts/index-jira-tests.ts`. Do not edit by hand.');
  out.push(
    '> Metadata only. Fetch test steps / definition via `jira_get_issue(key=…)` through Atlassian MCP.',
  );
  out.push(`> JQL: \`${jql}\``);
  out.push('');
  out.push('## Totals by Status');
  out.push('');
  const byStatus: Record<string, number> = {};
  for (const i of issues) byStatus[i.status] = (byStatus[i.status] ?? 0) + 1;
  out.push('| Status | Count |');
  out.push('|---|---|');
  for (const [s, c] of Object.entries(byStatus).sort((a, b) => b[1] - a[1])) {
    out.push(`| ${s} | ${c} |`);
  }
  out.push('');
  out.push('## Tests');
  out.push('');
  out.push('| Key | Summary | Status | Priority | Labels | Components | Updated |');
  out.push('|---|---|---|---|---|---|---|');
  for (const i of issues) {
    const summary = i.summary.replace(/\|/g, '\\|');
    out.push(
      `| ${i.key} | ${summary} | ${i.status} | ${i.priority} | ${i.labels.join(' ')} | ${i.components.join('; ')} | ${i.updated} |`,
    );
  }
  out.push('');
  fs.writeFileSync(OUTPUT, out.join('\n'), 'utf8');
}

function updateSyncState(count: number, jql: string): void {
  if (!fs.existsSync(SYNC_STATE)) return;
  const state = JSON.parse(fs.readFileSync(SYNC_STATE, 'utf8'));
  state.jiraTests = { jql, count, lastIndexed: new Date().toISOString() };
  fs.writeFileSync(SYNC_STATE, JSON.stringify(state, null, 2) + '\n', 'utf8');
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  const base = process.env.JIRA_BASE_URL ?? process.env.JIRA_URL ?? '';
  const email = process.env.JIRA_EMAIL ?? process.env.JIRA_USERNAME ?? '';
  const token = process.env.JIRA_API_TOKEN ?? '';

  if (!base || !email || !token) {
    console.error(
      'Missing JIRA_BASE_URL / JIRA_EMAIL / JIRA_API_TOKEN. Source your .env first.',
    );
    process.exit(2);
  }
  const auth = 'Basic ' + Buffer.from(`${email}:${token}`).toString('base64');

  const jql =
    args.jql ??
    `project = ${args.project} AND issuetype = Test ORDER BY updated DESC`;

  console.log(`Fetching tests via JQL (limit=${args.limit}):\n  ${jql}\n`);

  let issues: TestMeta[];
  try {
    issues = await searchJql(base, auth, jql, args.limit);
  } catch (err) {
    console.error(`Jira fetch failed: ${(err as Error).message}`);
    process.exit(1);
  }

  if (args.dryRun) {
    console.log(`Would write ${issues.length} rows to ${OUTPUT}`);
    return;
  }

  writeIndex(issues, jql);
  updateSyncState(issues.length, jql);
  console.log(`Wrote ${OUTPUT} — ${issues.length} tests indexed.`);
}

main();
