#!/usr/bin/env npx tsx
/**
 * Scenario Index Generator
 *
 * Reads config/scenarios.db and produces a metadata-only aggregate into
 * docs/ai/knowledge-base/corpus/scenario-index.md.
 *
 * Design rule: NEVER dump full scenarios here. Full rows are queried via
 * `npm run tracker:list -- --feature-area=<area>` on demand.
 */

import fs from 'fs';
import path from 'path';
import { getDb, closeDb } from '../src/tracker/db';

interface AreaTotals {
  area: string;
  total: number;
  automated: number;
  pending: number;
  onHold: number;
  passed: number;
  failed: number;
}

interface PrefixRow {
  area: string;
  prefix: string;
  count: number;
}

const OUTPUT = path.resolve(
  __dirname,
  '..',
  'docs',
  'ai',
  'knowledge-base',
  'corpus',
  'scenario-index.md',
);
const SYNC_STATE = path.resolve(
  __dirname,
  '..',
  'docs',
  'ai',
  'knowledge-base',
  '.sync-state.json',
);

function main(): void {
  const db = getDb();

  const areaRows = db
    .prepare(
      `SELECT
         feature_area AS area,
         COUNT(*) AS total,
         SUM(CASE WHEN automation_state = 'automated'     THEN 1 ELSE 0 END) AS automated,
         SUM(CASE WHEN automation_state = 'pending'       THEN 1 ELSE 0 END) AS pending,
         SUM(CASE WHEN automation_state = 'on-hold'       THEN 1 ELSE 0 END) AS onHold,
         SUM(CASE WHEN execution_status = 'passed'        THEN 1 ELSE 0 END) AS passed,
         SUM(CASE WHEN execution_status = 'failed-defect' THEN 1 ELSE 0 END) AS failed
       FROM scenarios
       GROUP BY feature_area
       ORDER BY feature_area`,
    )
    .all() as AreaTotals[];

  // Derive prefix = everything before the last "-###" numeric group.
  const prefixRows = db
    .prepare(
      `SELECT
         feature_area AS area,
         CASE
           WHEN id GLOB '*-[0-9][0-9][0-9]' THEN substr(id, 1, length(id) - 4)
           WHEN id GLOB '*-[0-9][0-9]'      THEN substr(id, 1, length(id) - 3)
           WHEN id GLOB '*-[0-9]'           THEN substr(id, 1, length(id) - 2)
           ELSE id
         END AS prefix,
         COUNT(*) AS count
       FROM scenarios
       GROUP BY area, prefix
       ORDER BY area, count DESC, prefix`,
    )
    .all() as PrefixRow[];

  const lines: string[] = [];
  lines.push('# Scenario Index');
  lines.push('');
  lines.push('> Generated by `scripts/index-scenarios.ts`. Do not edit by hand.');
  lines.push(
    '> Aggregated counts only. Query full scenario rows via `npm run tracker:list -- --feature-area=<area>`.',
  );
  lines.push('');
  lines.push('## Per-Area Totals');
  lines.push('');
  lines.push('| Area | Total | Automated | Pending | On-Hold | Passed | Failed |');
  lines.push('|---|---|---|---|---|---|---|');
  for (const r of areaRows) {
    lines.push(
      `| ${r.area} | ${r.total} | ${r.automated} | ${r.pending} | ${r.onHold} | ${r.passed} | ${r.failed} |`,
    );
  }
  lines.push('');
  lines.push('## Per-Area Scenario-ID Prefixes');
  lines.push('');
  lines.push('| Area | Prefix | Count |');
  lines.push('|---|---|---|');
  for (const r of prefixRows) {
    lines.push(`| ${r.area} | \`${r.prefix}\` | ${r.count} |`);
  }
  lines.push('');

  fs.writeFileSync(OUTPUT, lines.join('\n'), 'utf8');
  updateSyncState();
  closeDb();

  console.log(
    `Wrote ${OUTPUT} — ${areaRows.length} areas, ${prefixRows.length} prefixes.`,
  );
}

function updateSyncState(): void {
  if (!fs.existsSync(SYNC_STATE)) return;
  const state = JSON.parse(fs.readFileSync(SYNC_STATE, 'utf8'));
  state.scenarios ??= {};
  state.scenarios.db = 'config/scenarios.db';
  state.scenarios.lastIndexed = new Date().toISOString();
  fs.writeFileSync(SYNC_STATE, JSON.stringify(state, null, 2) + '\n', 'utf8');
}

main();
