#!/usr/bin/env npx tsx

import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(__dirname, '..');
const STORIES_INDEX = path.join(
  ROOT,
  'docs',
  'ai',
  'knowledge-base',
  'corpus',
  'jira-stories-index.md',
);
const REGISTRY_DIR = path.join(
  ROOT,
  'docs',
  'ai',
  'knowledge-base',
  'feature-registry',
);
const OUTPUT = path.join(
  ROOT,
  'docs',
  'ai',
  'knowledge-base',
  'corpus',
  'jira-story-feature-map.md',
);

type Story = {
  key: string;
  summary: string;
  status: string;
};

type Feature = {
  area: string;
  featureId: string;
  description: string;
  tokens: string[];
};

const STOP_WORDS = new Set([
  'a',
  'an',
  'and',
  'at',
  'be',
  'by',
  'for',
  'from',
  'in',
  'into',
  'is',
  'it',
  'list',
  'new',
  'of',
  'on',
  'or',
  'screen',
  'tab',
  'the',
  'to',
  'ui',
  'view',
  'with',
]);

const AREA_KEYWORDS: Record<string, string[]> = {
  auth: ['login', 'log', 'sso', 'ping', 'session', 'authentication'],
  landing: ['landing', 'task', 'tasks', 'notification', 'menu', 'search', 'my'],
  products: ['product', 'products', 'onboarding'],
  releases: [
    'release',
    'releases',
    'questionnaire',
    'requirement',
    'requirements',
    'csrr',
    'fcsr',
    'sign',
    'off',
    'action',
    'actions',
    'privacy',
    'scope',
  ],
  doc: ['doc', 'digital', 'offer', 'certification', 'control'],
  reports: ['report', 'reports', 'dashboard', 'dashboards', 'tableau'],
  backoffice: [
    'backoffice',
    'admin',
    'role',
    'roles',
    'privilege',
    'privileges',
    'organization',
    'configuration',
    'config',
    'ref',
    'data',
  ],
  integrations: ['jira', 'jama', 'api', 'webhook', 'ingestion', 'extraction'],
};

function normalize(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function tokenize(value: string): string[] {
  return normalize(value)
    .split(/\s+/)
    .filter((token) => token.length > 1 && !STOP_WORDS.has(token));
}

function parseStories(): Story[] {
  const text = fs.readFileSync(STORIES_INDEX, 'utf8');
  const stories: Story[] = [];

  for (const line of text.split('\n')) {
    if (!line.startsWith('| PIC-')) {
      continue;
    }

    const cells = line
      .split('|')
      .slice(1, -1)
      .map((cell) => cell.trim());

    if (cells.length < 3) {
      continue;
    }

    stories.push({
      key: cells[0],
      summary: cells[1].replace(/\\\|/g, '|'),
      status: cells[2],
    });
  }

  return stories;
}

function parseFeatures(): Feature[] {
  const features: Feature[] = [];
  const files = fs
    .readdirSync(REGISTRY_DIR)
    .filter((file) => file.endsWith('.md') && file !== '_template.md');

  for (const file of files) {
    const area = path.basename(file, '.md');
    const text = fs.readFileSync(path.join(REGISTRY_DIR, file), 'utf8');
    for (const line of text.split('\n')) {
      if (!line.startsWith('| ') || line.startsWith('| Feature ID ')) {
        continue;
      }
      const cells = line
        .split('|')
        .slice(1, -1)
        .map((cell) => cell.trim());
      if (cells.length < 2 || !cells[0] || cells[0] === '---') {
        continue;
      }
      if (!cells[0].includes('.')) {
        continue;
      }
      features.push({
        area,
        featureId: cells[0],
        description: cells[1],
        tokens: tokenize(`${cells[0]} ${cells[1]}`),
      });
    }
  }

  return features;
}

function inferArea(summaryTokens: string[]): string {
  let bestArea = 'other';
  let bestScore = 0;

  for (const [area, keywords] of Object.entries(AREA_KEYWORDS)) {
    let score = 0;
    for (const keyword of keywords) {
      if (summaryTokens.includes(keyword)) {
        score += 1;
      }
    }
    if (score > bestScore) {
      bestScore = score;
      bestArea = area;
    }
  }

  return bestArea;
}

function overlapScore(summaryTokens: string[], featureTokens: string[]): number {
  const featureTokenSet = new Set(featureTokens);
  let score = 0;
  for (const token of summaryTokens) {
    if (featureTokenSet.has(token)) {
      score += 1;
    }
  }
  return score;
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|');
}

function main(): void {
  const stories = parseStories();
  const features = parseFeatures();
  const lines: string[] = [];

  lines.push('# Jira Story → Feature Map');
  lines.push('');
  lines.push('> Generated by `scripts/map-jira-stories-to-features.ts`. Do not edit by hand.');
  lines.push('> Scope: user stories only. Source corpus: `corpus/jira-stories-index.md`.');
  lines.push('> Purpose: lightweight mapping from implemented Jira stories to KB feature areas and candidate `feature-id`s.');
  lines.push('');
  lines.push('| Story Key | Summary | Status | Area Guess | Candidate Feature IDs | Mapping Status |');
  lines.push('| --- | --- | --- | --- | --- | --- |');

  for (const story of stories) {
    const summaryTokens = tokenize(story.summary);
    const area = inferArea(summaryTokens);
    const candidates = features
      .filter((feature) => feature.area === area)
      .map((feature) => ({
        featureId: feature.featureId,
        score: overlapScore(summaryTokens, feature.tokens),
      }))
      .filter((item) => item.score > 0)
      .sort((left, right) => right.score - left.score || left.featureId.localeCompare(right.featureId))
      .slice(0, 3)
      .map((item) => item.featureId);

    const mappingStatus = candidates.length > 0 ? 'auto-candidate' : 'needs-review';
    lines.push(
      `| ${story.key} | ${escapeCell(story.summary)} | ${story.status} | ${area} | ${candidates.join(', ')} | ${mappingStatus} |`,
    );
  }

  lines.push('');
  fs.writeFileSync(OUTPUT, lines.join('\n'), 'utf8');
  console.log(`Wrote ${OUTPUT} — ${stories.length} user stories mapped.`);
}

main();